import { useState, useEffect, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  BarChart3,
  TrendingUp,
  TrendingDown,
  Lightbulb,
  Clock,
  Zap,
  RefreshCw,
  ArrowLeft,
  AlertTriangle,
  CheckCircle2,
  Target,
  Sparkles,
  Search,
  Filter,
  Download,
  Activity,
  Calendar,
  FileCode,
  XCircle,
  HelpCircle,
  Loader2,
  ChevronRight,
  Brain,
  MessageSquare,
  FolderCode,
  Package,
  Code2,
  FileText,
  ExternalLink,
  Briefcase,
  Rocket,
} from "lucide-react";
import { Link } from "wouter";
import { useToast } from "@/hooks/use-toast";
import type { AnalyticsOverview, Insight, LLMSettings, AnalyticsEvent } from "@shared/schema";

interface AnalyticsPageProps {
  settings: LLMSettings;
}

interface QueryResult {
  answer: string;
  data?: any;
  visualization?: "bar" | "line" | "pie" | "number" | "list";
}

interface ProjectInventory {
  id: string;
  name: string;
  description?: string;
  files: Array<{ path: string; language: string; lines: number; size: number }>;
  totalFiles: number;
  totalLines: number;
  totalSize: number;
  languageCounts: Record<string, number>;
  createdAt: number;
  updatedAt: number;
  hasCode: boolean;
  prompt?: string;
}

interface CodeInventory {
  summary: {
    totalProjects: number;
    projectsWithCode: number;
    totalFiles: number;
    totalLines: number;
    totalSize: number;
    averageLinesPerProject: number;
  };
  languageBreakdown: Record<string, { lines: number; files: number; projects: number }>;
  projects: ProjectInventory[];
}

export default function AnalyticsPage({ settings }: AnalyticsPageProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [nlQuery, setNlQuery] = useState("");
  const [queryResult, setQueryResult] = useState<QueryResult | null>(null);
  const [isQuerying, setIsQuerying] = useState(false);
  const [dateFilter, setDateFilter] = useState("30d");
  const [statusFilter, setStatusFilter] = useState("all");
  const [selectedMetric, setSelectedMetric] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  
  const { data: overview, isLoading: overviewLoading, refetch: refetchOverview } = useQuery<AnalyticsOverview>({
    queryKey: ["/api/analytics/overview"],
  });

  const { data: insights = [], isLoading: insightsLoading, refetch: refetchInsights } = useQuery<Insight[]>({
    queryKey: ["/api/analytics/insights"],
  });

  const { data: events = [] } = useQuery<AnalyticsEvent[]>({
    queryKey: ["/api/analytics/events"],
  });

  const { data: codeInventory, isLoading: inventoryLoading } = useQuery<CodeInventory>({
    queryKey: ["/api/analytics/code-inventory"],
  });

  const [selectedProject, setSelectedProject] = useState<string | null>(null);
  const [isExporting, setIsExporting] = useState(false);

  const generateInsightsMutation = useMutation({
    mutationFn: async () => {
      const response = await fetch("/api/analytics/generate-insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ settings }),
      });
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/analytics/insights"] });
    },
    onError: () => {
      toast({
        title: "Insights generation unavailable",
        description: "Connect to LM Studio for AI-powered insights.",
        variant: "destructive",
      });
    },
  });

  // Auto-generate insights on page load if none exist
  useEffect(() => {
    if (!insightsLoading && insights.length === 0 && !hasAutoGenerated && overview && overview.totalGenerations > 0) {
      setHasAutoGenerated(true);
      generateInsightsMutation.mutate();
    }
  }, [insightsLoading, insights.length, hasAutoGenerated, overview]);

  // Natural language query handler
  const handleNLQuery = async () => {
    if (!nlQuery.trim()) return;
    
    setIsQuerying(true);
    try {
      const response = await fetch("/api/analytics/query", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: nlQuery, settings }),
      });
      
      if (response.ok) {
        const result = await response.json();
        setQueryResult(result);
      } else {
        // Fallback: process query locally if LLM unavailable
        const localResult = processQueryLocally(nlQuery, overview, events);
        setQueryResult(localResult);
      }
    } catch (error) {
      const localResult = processQueryLocally(nlQuery, overview, events);
      setQueryResult(localResult);
    } finally {
      setIsQuerying(false);
    }
  };

  // Local query processing when LLM is unavailable
  const processQueryLocally = (query: string, data: AnalyticsOverview | undefined, allEvents: AnalyticsEvent[]): QueryResult => {
    const q = query.toLowerCase();
    
    if (!data) {
      return { answer: "No analytics data available yet. Start generating apps to see insights.", visualization: "number" };
    }

    if (q.includes("success") && q.includes("rate")) {
      return {
        answer: `Your success rate is ${data.successRate.toFixed(1)}%. Out of ${data.totalGenerations} total generations, ${data.successfulGenerations} were successful and ${data.failedGenerations} failed.`,
        data: { successRate: data.successRate, successful: data.successfulGenerations, failed: data.failedGenerations },
        visualization: "number"
      };
    }

    if (q.includes("total") || q.includes("how many") || q.includes("count")) {
      return {
        answer: `You have ${data.totalGenerations} total generations in the last 30 days. ${data.successfulGenerations} successful, ${data.failedGenerations} failed.`,
        data: { total: data.totalGenerations },
        visualization: "number"
      };
    }

    if (q.includes("template") || q.includes("popular")) {
      const templates = Object.entries(data.templateUsage).sort(([,a], [,b]) => b - a);
      if (templates.length === 0) {
        return { answer: "No template usage data available yet.", visualization: "list" };
      }
      const topTemplate = templates[0];
      return {
        answer: `The most popular template is "${topTemplate[0]}" with ${topTemplate[1]} uses. Here's the full breakdown:`,
        data: data.templateUsage,
        visualization: "bar"
      };
    }

    if (q.includes("time") || q.includes("fast") || q.includes("slow") || q.includes("duration")) {
      return {
        answer: `Average generation time is ${(data.averageGenerationTime / 1000).toFixed(1)} seconds per generation.`,
        data: { avgTime: data.averageGenerationTime },
        visualization: "number"
      };
    }

    if (q.includes("trend") || q.includes("week") || q.includes("day")) {
      const totalThisWeek = data.recentTrends.reduce((sum, day) => sum + day.generations, 0);
      const avgPerDay = (totalThisWeek / 7).toFixed(1);
      return {
        answer: `In the last 7 days, you had ${totalThisWeek} generations (average ${avgPerDay} per day).`,
        data: data.recentTrends,
        visualization: "bar"
      };
    }

    if (q.includes("error") || q.includes("fail") || q.includes("problem")) {
      const errorEvents = allEvents.filter(e => e.type === "generation_failed" || e.type === "error_occurred");
      if (errorEvents.length === 0) {
        return { answer: "Great news! No errors recorded in your recent history.", visualization: "number" };
      }
      const errorTypes: Record<string, number> = {};
      errorEvents.forEach(e => {
        const type = e.data?.errorType || "unknown";
        errorTypes[type] = (errorTypes[type] || 0) + 1;
      });
      return {
        answer: `Found ${errorEvents.length} errors. Here's the breakdown by type:`,
        data: errorTypes,
        visualization: "bar"
      };
    }

    return {
      answer: `Based on your data: ${data.totalGenerations} total generations with ${data.successRate.toFixed(1)}% success rate. Average time: ${(data.averageGenerationTime / 1000).toFixed(1)}s. Try asking about success rates, templates, trends, or errors.`,
      visualization: "number"
    };
  };

  // Filter events based on selected filters
  const filteredEvents = useMemo(() => {
    let filtered = [...events];
    
    // Date filter
    const now = Date.now();
    const filterMs = {
      "7d": 7 * 24 * 60 * 60 * 1000,
      "30d": 30 * 24 * 60 * 60 * 1000,
      "90d": 90 * 24 * 60 * 60 * 1000,
      "all": Infinity
    }[dateFilter] || 30 * 24 * 60 * 60 * 1000;
    
    if (filterMs !== Infinity) {
      filtered = filtered.filter(e => e.timestamp >= now - filterMs);
    }

    // Status filter
    if (statusFilter === "success") {
      filtered = filtered.filter(e => e.type === "generation_completed");
    } else if (statusFilter === "failed") {
      filtered = filtered.filter(e => e.type === "generation_failed" || e.type === "error_occurred");
    }

    return filtered;
  }, [events, dateFilter, statusFilter]);

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "high": return "destructive";
      case "medium": return "default";
      case "low": return "secondary";
      default: return "outline";
    }
  };

  const getInsightIcon = (type: string) => {
    switch (type) {
      case "pattern": return <BarChart3 className="h-4 w-4" />;
      case "recommendation": return <Lightbulb className="h-4 w-4" />;
      case "trend": return <TrendingUp className="h-4 w-4" />;
      case "warning": return <AlertTriangle className="h-4 w-4" />;
      default: return <Sparkles className="h-4 w-4" />;
    }
  };

  const getEventIcon = (type: string) => {
    switch (type) {
      case "generation_completed": return <CheckCircle2 className="h-4 w-4 text-green-500" />;
      case "generation_failed": return <XCircle className="h-4 w-4 text-red-500" />;
      case "generation_started": return <Activity className="h-4 w-4 text-blue-500" />;
      case "error_occurred": return <AlertTriangle className="h-4 w-4 text-yellow-500" />;
      default: return <FileCode className="h-4 w-4 text-muted-foreground" />;
    }
  };

  // Quick insights based on data
  const quickInsights = useMemo(() => {
    if (!overview) return [];
    const insights: string[] = [];
    
    if (overview.successRate >= 90) {
      insights.push("Excellent success rate! Your prompts are working well.");
    } else if (overview.successRate < 50) {
      insights.push("Low success rate detected. Consider simplifying your prompts.");
    }
    
    if (overview.averageGenerationTime > 30000) {
      insights.push("Generation times are slow. Try using a smaller LLM model.");
    }
    
    const templates = Object.entries(overview.templateUsage);
    if (templates.length > 0) {
      const top = templates.sort(([,a], [,b]) => b - a)[0];
      insights.push(`"${top[0]}" is your most used template.`);
    }

    const todayTrend = overview.recentTrends[overview.recentTrends.length - 1];
    if (todayTrend && todayTrend.generations > 0) {
      insights.push(`${todayTrend.generations} generations today.`);
    }

    return insights;
  }, [overview]);

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-7xl mx-auto p-6">
        {/* Header */}
        <div className="flex items-center justify-between gap-4 mb-6 flex-wrap">
          <div className="flex items-center gap-4">
            <Link href="/">
              <Button variant="ghost" size="icon" data-testid="button-back-home">
                <ArrowLeft className="h-4 w-4" />
              </Button>
            </Link>
            <div>
              <h1 className="text-2xl font-bold flex items-center gap-2">
                <Brain className="h-6 w-6 text-primary" />
                Analytics Studio
              </h1>
              <p className="text-muted-foreground">
                Self-service analytics for your LocalForge usage
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              onClick={() => {
                refetchOverview();
                refetchInsights();
              }}
              data-testid="button-refresh"
            >
              <RefreshCw className="h-4 w-4 mr-2" />
              Refresh
            </Button>
          </div>
        </div>

        {/* Natural Language Query Bar */}
        <Card className="mb-6 border-primary/20 bg-gradient-to-r from-primary/5 to-transparent">
          <CardContent className="pt-4">
            <div className="flex items-center gap-2">
              <MessageSquare className="h-5 w-5 text-primary" />
              <span className="font-medium">Ask anything about your data</span>
            </div>
            <div className="flex gap-2 mt-3">
              <Input
                placeholder="e.g., 'What's my success rate?' or 'Show me the most popular templates'"
                value={nlQuery}
                onChange={(e) => setNlQuery(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleNLQuery()}
                className="flex-1"
                data-testid="input-nl-query"
              />
              <Button 
                onClick={handleNLQuery} 
                disabled={isQuerying || !nlQuery.trim()}
                data-testid="button-query"
              >
                {isQuerying ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Search className="h-4 w-4" />
                )}
              </Button>
            </div>
            <div className="flex gap-2 mt-2 flex-wrap">
              {["What's my success rate?", "Show trends", "Most popular template", "Any errors?"].map((suggestion) => (
                <Button
                  key={suggestion}
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setNlQuery(suggestion);
                    setTimeout(handleNLQuery, 100);
                  }}
                  data-testid={`suggestion-${suggestion.replace(/\s+/g, '-').toLowerCase()}`}
                >
                  {suggestion}
                </Button>
              ))}
            </div>

            {/* Query Result */}
            {queryResult && (
              <div className="mt-4 p-4 bg-background rounded-lg border">
                <p className="text-sm">{queryResult.answer}</p>
                {queryResult.data && queryResult.visualization === "bar" && (
                  <div className="mt-3 space-y-2">
                    {Object.entries(queryResult.data as Record<string, number>)
                      .sort(([,a], [,b]) => b - a)
                      .slice(0, 5)
                      .map(([key, value]) => {
                        const max = Math.max(...Object.values(queryResult.data as Record<string, number>));
                        return (
                          <div key={key} className="space-y-1">
                            <div className="flex justify-between gap-2 text-xs">
                              <span className="capitalize">{key.replace(/_/g, " ")}</span>
                              <span>{value}</span>
                            </div>
                            <div className="h-2 bg-muted rounded-full overflow-hidden">
                              <div 
                                className="h-full bg-primary transition-all"
                                style={{ width: `${(value / max) * 100}%` }}
                              />
                            </div>
                          </div>
                        );
                      })}
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Quick Stats */}
        {overviewLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            {[...Array(4)].map((_, i) => (
              <Card key={i} className="animate-pulse">
                <CardHeader className="pb-2">
                  <div className="h-4 bg-muted rounded w-1/2" />
                </CardHeader>
                <CardContent>
                  <div className="h-8 bg-muted rounded w-1/3" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : overview ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <Card 
              className={`cursor-pointer hover-elevate ${selectedMetric === 'generations' ? 'ring-2 ring-primary' : ''}`}
              onClick={() => setSelectedMetric(selectedMetric === 'generations' ? null : 'generations')}
              data-testid="metric-total-generations"
            >
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                <CardTitle className="text-sm font-medium">Total Generations</CardTitle>
                <Zap className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">{overview.totalGenerations}</div>
                <p className="text-xs text-muted-foreground">Last 30 days</p>
              </CardContent>
            </Card>

            <Card 
              className={`cursor-pointer hover-elevate ${selectedMetric === 'success' ? 'ring-2 ring-primary' : ''}`}
              onClick={() => setSelectedMetric(selectedMetric === 'success' ? null : 'success')}
              data-testid="metric-success-rate"
            >
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                <CardTitle className="text-sm font-medium">Success Rate</CardTitle>
                {overview.successRate >= 80 ? (
                  <TrendingUp className="h-4 w-4 text-green-500" />
                ) : (
                  <TrendingDown className="h-4 w-4 text-red-500" />
                )}
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">{overview.successRate.toFixed(1)}%</div>
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <span className="flex items-center gap-1">
                    <CheckCircle2 className="h-3 w-3 text-green-500" />
                    {overview.successfulGenerations}
                  </span>
                  <span className="flex items-center gap-1">
                    <XCircle className="h-3 w-3 text-red-500" />
                    {overview.failedGenerations}
                  </span>
                </div>
              </CardContent>
            </Card>

            <Card 
              className={`cursor-pointer hover-elevate ${selectedMetric === 'time' ? 'ring-2 ring-primary' : ''}`}
              onClick={() => setSelectedMetric(selectedMetric === 'time' ? null : 'time')}
              data-testid="metric-avg-time"
            >
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                <CardTitle className="text-sm font-medium">Avg. Generation Time</CardTitle>
                <Clock className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">
                  {(overview.averageGenerationTime / 1000).toFixed(1)}s
                </div>
                <p className="text-xs text-muted-foreground">Per generation</p>
              </CardContent>
            </Card>

            <Card 
              className={`cursor-pointer hover-elevate ${selectedMetric === 'activity' ? 'ring-2 ring-primary' : ''}`}
              onClick={() => setSelectedMetric(selectedMetric === 'activity' ? null : 'activity')}
              data-testid="metric-activity"
            >
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                <CardTitle className="text-sm font-medium">Today's Activity</CardTitle>
                <Activity className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold">
                  {overview.recentTrends[overview.recentTrends.length - 1]?.generations || 0}
                </div>
                <p className="text-xs text-muted-foreground">Generations today</p>
              </CardContent>
            </Card>
          </div>
        ) : null}

        {/* Quick Insights Banner */}
        {quickInsights.length > 0 && (
          <Card className="mb-6 bg-gradient-to-r from-amber-500/10 to-orange-500/10 border-amber-500/20">
            <CardContent className="py-3">
              <div className="flex items-center gap-2 text-sm">
                <Lightbulb className="h-4 w-4 text-amber-500" />
                <span className="font-medium text-amber-700 dark:text-amber-300">Quick Insights:</span>
                <span className="text-muted-foreground">{quickInsights.join(" • ")}</span>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Main Content Tabs */}
        <Tabs defaultValue="dashboard" className="space-y-6">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <TabsList data-testid="analytics-tabs">
              <TabsTrigger value="dashboard" data-testid="tab-dashboard">
                <BarChart3 className="h-4 w-4 mr-2" />
                Dashboard
              </TabsTrigger>
              <TabsTrigger value="insights" data-testid="tab-insights">
                <Lightbulb className="h-4 w-4 mr-2" />
                AI Insights
                {insights.length > 0 && (
                  <Badge variant="secondary" className="ml-2">{insights.length}</Badge>
                )}
              </TabsTrigger>
              <TabsTrigger value="explorer" data-testid="tab-explorer">
                <Search className="h-4 w-4 mr-2" />
                Data Explorer
              </TabsTrigger>
              <TabsTrigger value="portfolio" data-testid="tab-portfolio">
                <FolderCode className="h-4 w-4 mr-2" />
                <span data-testid="tab-portfolio-label">Portfolio</span>
                {codeInventory && codeInventory.summary.projectsWithCode > 0 && (
                  <Badge variant="secondary" className="ml-2" data-testid="badge-portfolio-count">{codeInventory.summary.projectsWithCode}</Badge>
                )}
              </TabsTrigger>
            </TabsList>

            {/* Filters */}
            <div className="flex items-center gap-2">
              <Select value={dateFilter} onValueChange={setDateFilter}>
                <SelectTrigger className="w-32" data-testid="select-date-filter">
                  <Calendar className="h-4 w-4 mr-2" />
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="7d" data-testid="select-item-7d">Last 7 days</SelectItem>
                  <SelectItem value="30d" data-testid="select-item-30d">Last 30 days</SelectItem>
                  <SelectItem value="90d" data-testid="select-item-90d">Last 90 days</SelectItem>
                  <SelectItem value="all" data-testid="select-item-all">All time</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Dashboard Tab */}
          <TabsContent value="dashboard" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Template Usage */}
              <Card data-testid="card-template-usage">
                <CardHeader>
                  <CardTitle className="text-base">Template Usage</CardTitle>
                  <CardDescription>Which templates are most popular</CardDescription>
                </CardHeader>
                <CardContent>
                  {overview && Object.keys(overview.templateUsage).length > 0 ? (
                    <div className="space-y-3">
                      {Object.entries(overview.templateUsage)
                        .sort(([, a], [, b]) => b - a)
                        .map(([template, count]) => {
                          const total = Object.values(overview.templateUsage).reduce((a, b) => a + b, 0);
                          const percentage = (count / total) * 100;
                          return (
                            <div key={template} className="space-y-1">
                              <div className="flex items-center justify-between text-sm">
                                <span className="capitalize">{template.replace(/_/g, " ")}</span>
                                <span className="text-muted-foreground">{count} ({percentage.toFixed(0)}%)</span>
                              </div>
                              <div className="h-2 bg-muted rounded-full overflow-hidden">
                                <div 
                                  className="h-full bg-primary transition-all"
                                  style={{ width: `${percentage}%` }}
                                />
                              </div>
                            </div>
                          );
                        })}
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground">No template usage data yet</p>
                  )}
                </CardContent>
              </Card>

              {/* 7-Day Trend */}
              <Card data-testid="card-recent-trends">
                <CardHeader>
                  <CardTitle className="text-base">7-Day Trend</CardTitle>
                  <CardDescription>Generation activity over the past week</CardDescription>
                </CardHeader>
                <CardContent>
                  {overview && (
                    <div className="space-y-3">
                      {overview.recentTrends.map((day) => {
                        const maxGenerations = Math.max(...overview.recentTrends.map(d => d.generations), 1);
                        const successRate = day.generations > 0 ? (day.successes / day.generations) * 100 : 0;
                        return (
                          <div key={day.date} className="flex items-center gap-4">
                            <span className="text-sm text-muted-foreground w-20">
                              {new Date(day.date).toLocaleDateString("en-US", { 
                                weekday: "short", 
                                month: "short", 
                                day: "numeric" 
                              })}
                            </span>
                            <div className="flex-1">
                              <div className="h-6 bg-muted rounded overflow-hidden flex">
                                <div 
                                  className="h-full bg-green-500 transition-all"
                                  style={{ width: `${(day.successes / maxGenerations) * 100}%` }}
                                />
                                <div 
                                  className="h-full bg-red-500 transition-all"
                                  style={{ width: `${((day.generations - day.successes) / maxGenerations) * 100}%` }}
                                />
                              </div>
                            </div>
                            <div className="w-16 text-right">
                              <span className="text-sm font-medium">{day.generations}</span>
                              {day.generations > 0 && (
                                <span className="text-xs text-muted-foreground ml-1">
                                  ({successRate.toFixed(0)}%)
                                </span>
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Performance Distribution */}
              <Card data-testid="card-performance">
                <CardHeader>
                  <CardTitle className="text-base">Success vs Failure</CardTitle>
                  <CardDescription>Overall generation outcomes</CardDescription>
                </CardHeader>
                <CardContent>
                  {overview && overview.totalGenerations > 0 ? (
                    <div className="space-y-4">
                      <div className="flex items-center gap-4">
                        <div className="flex-1">
                          <div className="h-8 bg-muted rounded-full overflow-hidden flex">
                            <div 
                              className="h-full bg-green-500 flex items-center justify-center text-xs text-white font-medium"
                              style={{ width: `${overview.successRate}%` }}
                            >
                              {overview.successRate > 20 && `${overview.successRate.toFixed(0)}%`}
                            </div>
                            <div 
                              className="h-full bg-red-500 flex items-center justify-center text-xs text-white font-medium"
                              style={{ width: `${100 - overview.successRate}%` }}
                            >
                              {(100 - overview.successRate) > 20 && `${(100 - overview.successRate).toFixed(0)}%`}
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="flex justify-between gap-4 text-sm flex-wrap">
                        <div className="flex items-center gap-2">
                          <div className="w-3 h-3 rounded-full bg-green-500" />
                          <span>Success: {overview.successfulGenerations}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <div className="w-3 h-3 rounded-full bg-red-500" />
                          <span>Failed: {overview.failedGenerations}</span>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground">No generation data yet</p>
                  )}
                </CardContent>
              </Card>

              {/* Generation Time Stats */}
              <Card data-testid="card-time-stats">
                <CardHeader>
                  <CardTitle className="text-base">Generation Speed</CardTitle>
                  <CardDescription>How fast are your generations</CardDescription>
                </CardHeader>
                <CardContent>
                  {overview ? (
                    <div className="space-y-4">
                      <div className="text-center">
                        <div className="text-4xl font-bold text-primary">
                          {(overview.averageGenerationTime / 1000).toFixed(1)}s
                        </div>
                        <p className="text-sm text-muted-foreground">Average time per generation</p>
                      </div>
                      <div className="grid grid-cols-3 gap-4 pt-4 border-t">
                        <div className="text-center">
                          <div className="text-lg font-semibold text-green-500">
                            {overview.averageGenerationTime < 10000 ? "Fast" : overview.averageGenerationTime < 30000 ? "Normal" : "Slow"}
                          </div>
                          <p className="text-xs text-muted-foreground">Speed Rating</p>
                        </div>
                        <div className="text-center">
                          <div className="text-lg font-semibold">{overview.totalGenerations}</div>
                          <p className="text-xs text-muted-foreground">Total Runs</p>
                        </div>
                        <div className="text-center">
                          <div className="text-lg font-semibold">
                            {((overview.averageGenerationTime * overview.totalGenerations) / 60000).toFixed(1)}m
                          </div>
                          <p className="text-xs text-muted-foreground">Total Time</p>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground">No timing data yet</p>
                  )}
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          {/* AI Insights Tab */}
          <TabsContent value="insights" className="space-y-4">
            {generateInsightsMutation.isPending && (
              <Card className="border-primary/20">
                <CardContent className="py-6 flex items-center justify-center gap-3">
                  <Loader2 className="h-5 w-5 animate-spin text-primary" />
                  <span>Analyzing your data with AI...</span>
                </CardContent>
              </Card>
            )}

            {insightsLoading ? (
              <div className="space-y-4">
                {[...Array(3)].map((_, i) => (
                  <Card key={i} className="animate-pulse">
                    <CardHeader>
                      <div className="h-5 bg-muted rounded w-1/3" />
                    </CardHeader>
                    <CardContent>
                      <div className="h-4 bg-muted rounded w-2/3" />
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : insights.length > 0 ? (
              <ScrollArea className="h-[600px] pr-4">
                <div className="space-y-4">
                  {insights.map((insight) => (
                    <Card key={insight.id} data-testid={`insight-${insight.id}`}>
                      <CardHeader className="pb-2">
                        <div className="flex items-start justify-between gap-4">
                          <div className="flex items-center gap-2">
                            {getInsightIcon(insight.type)}
                            <CardTitle className="text-base">{insight.title}</CardTitle>
                          </div>
                          <div className="flex items-center gap-2">
                            <Badge variant={getPriorityColor(insight.priority)}>
                              {insight.priority}
                            </Badge>
                            <Badge variant="outline" className="capitalize">
                              {insight.type}
                            </Badge>
                          </div>
                        </div>
                      </CardHeader>
                      <CardContent>
                        <p className="text-sm text-muted-foreground">{insight.description}</p>
                        {insight.actionable && (
                          <div className="mt-3 flex items-center gap-2 text-sm text-primary">
                            <Target className="h-4 w-4" />
                            <span>Actionable recommendation</span>
                          </div>
                        )}
                        <div className="mt-2 text-xs text-muted-foreground">
                          Generated {new Date(insight.generatedAt).toLocaleDateString()}
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </ScrollArea>
            ) : (
              <Card>
                <CardContent className="py-12 text-center">
                  <Lightbulb className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                  <h3 className="text-lg font-medium mb-2">Generating Insights...</h3>
                  <p className="text-muted-foreground mb-4">
                    {overview && overview.totalGenerations > 0 
                      ? "AI is analyzing your usage patterns. This requires a connection to LM Studio."
                      : "Start generating apps to see AI-powered insights about your usage."}
                  </p>
                  {overview && overview.totalGenerations > 0 && (
                    <Button
                      onClick={() => generateInsightsMutation.mutate()}
                      disabled={generateInsightsMutation.isPending}
                      data-testid="button-generate-insights"
                    >
                      {generateInsightsMutation.isPending ? (
                        <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                      ) : (
                        <Sparkles className="h-4 w-4 mr-2" />
                      )}
                      Retry Insights Generation
                    </Button>
                  )}
                </CardContent>
              </Card>
            )}
          </TabsContent>

          {/* Data Explorer Tab */}
          <TabsContent value="explorer" className="space-y-4">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between gap-4 flex-wrap">
                  <div>
                    <CardTitle className="text-base">Event Log</CardTitle>
                    <CardDescription>Detailed history of all events</CardDescription>
                  </div>
                  <div className="flex items-center gap-2">
                    <Select value={statusFilter} onValueChange={setStatusFilter}>
                      <SelectTrigger className="w-32" data-testid="select-status-filter">
                        <Filter className="h-4 w-4 mr-2" />
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all" data-testid="status-all">All Events</SelectItem>
                        <SelectItem value="success" data-testid="status-success">Successful</SelectItem>
                        <SelectItem value="failed" data-testid="status-failed">Failed</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <ScrollArea className="h-[500px]">
                  {filteredEvents.length > 0 ? (
                    <div className="space-y-2">
                      {filteredEvents.slice(0, 100).map((event) => (
                        <div 
                          key={event.id} 
                          className="flex items-center gap-3 p-3 rounded-lg bg-muted/50 hover:bg-muted transition-colors"
                          data-testid={`event-${event.id}`}
                        >
                          {getEventIcon(event.type)}
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium capitalize">
                              {event.type.replace(/_/g, " ")}
                            </p>
                            {event.data && Object.keys(event.data).length > 0 && (
                              <p className="text-xs text-muted-foreground truncate">
                                {JSON.stringify(event.data).slice(0, 100)}
                              </p>
                            )}
                          </div>
                          <span className="text-xs text-muted-foreground whitespace-nowrap">
                            {new Date(event.timestamp).toLocaleString()}
                          </span>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="text-center py-12">
                      <Search className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                      <p className="text-muted-foreground">No events match your filters</p>
                    </div>
                  )}
                </ScrollArea>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Portfolio Tab */}
          <TabsContent value="portfolio" className="space-y-6">
            {/* Portfolio Summary Stats */}
            {inventoryLoading ? (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                {[...Array(4)].map((_, i) => (
                  <Card key={i} className="animate-pulse">
                    <CardHeader className="pb-2">
                      <div className="h-4 bg-muted rounded w-1/2" />
                    </CardHeader>
                    <CardContent>
                      <div className="h-8 bg-muted rounded w-1/3" />
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : codeInventory ? (
              <>
                {/* Portfolio Stats */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <Card data-testid="stat-total-projects">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                      <CardTitle className="text-sm font-medium">Total Projects</CardTitle>
                      <Briefcase className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-3xl font-bold">{codeInventory.summary.totalProjects}</div>
                      <p className="text-xs text-muted-foreground">
                        {codeInventory.summary.projectsWithCode} with code
                      </p>
                    </CardContent>
                  </Card>

                  <Card data-testid="stat-total-files">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                      <CardTitle className="text-sm font-medium">Total Files</CardTitle>
                      <FileText className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-3xl font-bold">{codeInventory.summary.totalFiles}</div>
                      <p className="text-xs text-muted-foreground">
                        Across all projects
                      </p>
                    </CardContent>
                  </Card>

                  <Card data-testid="stat-total-lines">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                      <CardTitle className="text-sm font-medium">Lines of Code</CardTitle>
                      <Code2 className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-3xl font-bold">{codeInventory.summary.totalLines.toLocaleString()}</div>
                      <p className="text-xs text-muted-foreground">
                        ~{codeInventory.summary.averageLinesPerProject} per project
                      </p>
                    </CardContent>
                  </Card>

                  <Card data-testid="stat-total-size">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
                      <CardTitle className="text-sm font-medium">Total Size</CardTitle>
                      <Package className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-3xl font-bold">
                        {(codeInventory.summary.totalSize / 1024).toFixed(1)} KB
                      </div>
                      <p className="text-xs text-muted-foreground">
                        Raw code size
                      </p>
                    </CardContent>
                  </Card>
                </div>

                {/* Language Breakdown & Actions */}
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {/* Language Breakdown */}
                  <Card data-testid="card-languages">
                    <CardHeader>
                      <CardTitle className="text-base">Language Breakdown</CardTitle>
                      <CardDescription>Technologies used across all projects</CardDescription>
                    </CardHeader>
                    <CardContent>
                      {Object.keys(codeInventory.languageBreakdown).length > 0 ? (
                        <div className="space-y-3">
                          {Object.entries(codeInventory.languageBreakdown)
                            .sort(([, a], [, b]) => b.lines - a.lines)
                            .map(([language, stats], index) => {
                              const totalLines = codeInventory.summary.totalLines;
                              const percentage = totalLines > 0 ? (stats.lines / totalLines) * 100 : 0;
                              const langKey = language.replace(/\s+/g, '-').toLowerCase();
                              const colorClasses = [
                                'bg-primary',
                                'bg-chart-1',
                                'bg-chart-2',
                                'bg-chart-3',
                                'bg-chart-4',
                                'bg-chart-5',
                                'bg-accent',
                                'bg-secondary',
                                'bg-muted-foreground',
                              ];
                              return (
                                <div key={language} className="space-y-1" data-testid={`lang-row-${langKey}`}>
                                  <div className="flex items-center justify-between gap-4 text-sm">
                                    <span className="font-medium" data-testid={`lang-name-${langKey}`}>{language}</span>
                                    <span className="text-muted-foreground" data-testid={`lang-stats-${langKey}`}>
                                      {stats.lines.toLocaleString()} lines ({percentage.toFixed(0)}%)
                                    </span>
                                  </div>
                                  <div className="h-2 bg-muted rounded-full overflow-hidden">
                                    <div 
                                      className={`h-full transition-all ${colorClasses[index % colorClasses.length]}`}
                                      style={{ width: `${percentage}%` }}
                                      data-testid={`lang-bar-${langKey}`}
                                    />
                                  </div>
                                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                                    <span data-testid={`lang-files-${langKey}`}>{stats.files} files</span>
                                    <span data-testid={`lang-projects-${langKey}`}>{stats.projects} projects</span>
                                  </div>
                                </div>
                              );
                            })}
                        </div>
                      ) : (
                        <p className="text-sm text-muted-foreground">No code generated yet</p>
                      )}
                    </CardContent>
                  </Card>

                  {/* Export & Actions */}
                  <Card data-testid="card-export">
                    <CardHeader>
                      <CardTitle className="text-base flex items-center gap-2">
                        <Rocket className="h-4 w-4" />
                        Local Packaging
                      </CardTitle>
                      <CardDescription>Export and manage your projects locally</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="p-4 bg-muted/50 rounded-lg">
                        <h4 className="font-medium mb-2">Your Product Portfolio</h4>
                        <p className="text-sm text-muted-foreground mb-4">
                          You have {codeInventory.summary.projectsWithCode} projects with generated code ready for local development or deployment.
                        </p>
                        <div className="space-y-2">
                          <Button
                            className="w-full"
                            onClick={async () => {
                              setIsExporting(true);
                              try {
                                const response = await fetch("/api/analytics/export-manifest");
                                if (!response.ok) {
                                  throw new Error(`Export failed: ${response.status}`);
                                }
                                const manifest = await response.json();
                                const blob = new Blob([JSON.stringify(manifest, null, 2)], { type: "application/json" });
                                const url = URL.createObjectURL(blob);
                                const a = document.createElement("a");
                                a.href = url;
                                a.download = `localforge-portfolio-${new Date().toISOString().split('T')[0]}.json`;
                                a.click();
                                URL.revokeObjectURL(url);
                                toast({ title: "Portfolio manifest exported!" });
                              } catch (error) {
                                toast({ title: "Export failed", description: "Could not generate portfolio manifest", variant: "destructive" });
                              } finally {
                                setIsExporting(false);
                              }
                            }}
                            disabled={isExporting}
                            data-testid="button-export-manifest"
                          >
                            {isExporting ? (
                              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                            ) : (
                              <Download className="h-4 w-4 mr-2" />
                            )}
                            Export Portfolio Manifest
                          </Button>
                        </div>
                      </div>

                      <div className="text-sm text-muted-foreground">
                        <p className="font-medium mb-1">Tips for Product Development:</p>
                        <ul className="list-disc list-inside space-y-1 text-xs">
                          <li>Use templates like "Task Manager" for validated product ideas</li>
                          <li>Iterate with refinements to polish your MVP</li>
                          <li>Download full-stack apps for local hosting</li>
                          <li>Track successful prompts for reusable patterns</li>
                        </ul>
                      </div>
                    </CardContent>
                  </Card>
                </div>

                {/* Project List */}
                <Card data-testid="card-project-list">
                  <CardHeader>
                    <CardTitle className="text-base">Project Inventory</CardTitle>
                    <CardDescription>All your generated apps with code details</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <ScrollArea className="h-[400px]">
                      {codeInventory.projects.filter(p => p.hasCode).length > 0 ? (
                        <div className="space-y-3">
                          {codeInventory.projects.filter(p => p.hasCode).map((project) => (
                            <div
                              key={project.id}
                              className={`p-4 rounded-lg border hover-elevate cursor-pointer ${
                                selectedProject === project.id ? 'ring-2 ring-primary' : ''
                              }`}
                              onClick={() => setSelectedProject(selectedProject === project.id ? null : project.id)}
                              data-testid={`project-${project.id}`}
                            >
                              <div className="flex items-start justify-between gap-4 flex-wrap">
                                <div className="flex-1 min-w-0">
                                  <h4 className="font-medium truncate" data-testid={`project-name-${project.id}`}>{project.name}</h4>
                                  {project.prompt && (
                                    <p className="text-xs text-muted-foreground line-clamp-2 mt-1" data-testid={`project-prompt-${project.id}`}>
                                      {project.prompt}
                                    </p>
                                  )}
                                </div>
                                <div className="flex items-center gap-2 flex-wrap">
                                  <Badge variant="secondary" data-testid={`project-files-count-${project.id}`}>{project.totalFiles} files</Badge>
                                  <Badge variant="outline" data-testid={`project-lines-count-${project.id}`}>{project.totalLines} lines</Badge>
                                </div>
                              </div>

                              {selectedProject === project.id && (
                                <div className="mt-4 pt-4 border-t space-y-3" data-testid={`project-details-${project.id}`}>
                                  {/* Languages used */}
                                  <div className="flex items-center gap-2 flex-wrap">
                                    {Object.entries(project.languageCounts).map(([lang, lines]) => (
                                      <Badge key={lang} variant="outline" className="text-xs" data-testid={`project-lang-${project.id}-${lang.replace(/\s+/g, '-').toLowerCase()}`}>
                                        {lang}: {lines} lines
                                      </Badge>
                                    ))}
                                  </div>

                                  {/* Files list */}
                                  <div className="space-y-1">
                                    {project.files.slice(0, 10).map((file, i) => (
                                      <div key={i} className="flex items-center justify-between gap-4 text-xs" data-testid={`project-file-${project.id}-${i}`}>
                                        <span className="font-mono truncate" data-testid={`project-file-path-${project.id}-${i}`}>{file.path}</span>
                                        <span className="text-muted-foreground whitespace-nowrap" data-testid={`project-file-lines-${project.id}-${i}`}>
                                          {file.lines} lines
                                        </span>
                                      </div>
                                    ))}
                                    {project.files.length > 10 && (
                                      <p className="text-xs text-muted-foreground" data-testid={`project-more-files-${project.id}`}>
                                        +{project.files.length - 10} more files
                                      </p>
                                    )}
                                  </div>

                                  {/* Actions */}
                                  <div className="flex items-center gap-2 flex-wrap">
                                    <Link href={`/?project=${project.id}`}>
                                      <Button size="sm" variant="outline" data-testid={`open-project-${project.id}`}>
                                        <ExternalLink className="h-3 w-3 mr-1" />
                                        Open Project
                                      </Button>
                                    </Link>
                                  </div>
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <div className="text-center py-12">
                          <FolderCode className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                          <h3 className="text-lg font-medium mb-2">No Projects Yet</h3>
                          <p className="text-muted-foreground mb-4">
                            Start building apps to see your portfolio grow
                          </p>
                          <Link href="/">
                            <Button data-testid="button-start-building">
                              <Rocket className="h-4 w-4 mr-2" />
                              Start Building
                            </Button>
                          </Link>
                        </div>
                      )}
                    </ScrollArea>
                  </CardContent>
                </Card>
              </>
            ) : null}
          </TabsContent>
        </Tabs>

        {/* No Data State */}
        {!overviewLoading && (!overview || overview.totalGenerations === 0) && (
          <Card className="mt-6">
            <CardContent className="py-12 text-center">
              <BarChart3 className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
              <h3 className="text-lg font-medium mb-2">No Analytics Data Yet</h3>
              <p className="text-muted-foreground mb-4">
                Start generating apps to see your analytics and AI-powered insights
              </p>
              <Link href="/">
                <Button data-testid="button-go-create">
                  Create Your First App
                </Button>
              </Link>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
