import type { DataModel } from "@shared/schema";
import { toKebabCase, pluralize } from "./utils";

export function generatePackageJson(projectName: string): string {
  return JSON.stringify({
    name: toKebabCase(projectName),
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "concurrently \"npm run dev:server\" \"npm run dev:client\"",
      "dev:server": "tsx watch server/index.ts",
      "dev:client": "vite",
      build: "vite build && tsc -p tsconfig.server.json",
      "db:push": "drizzle-kit push",
      "db:studio": "drizzle-kit studio"
    },
    dependencies: {
      "@hookform/resolvers": "^3.3.4",
      "@neondatabase/serverless": "^0.9.0",
      "@radix-ui/react-label": "^2.0.2",
      "@radix-ui/react-slot": "^1.0.2",
      "@radix-ui/react-switch": "^1.0.3",
      "@tanstack/react-query": "^5.28.0",
      "class-variance-authority": "^0.7.0",
      clsx: "^2.1.0",
      "drizzle-orm": "^0.30.4",
      "drizzle-zod": "^0.5.1",
      express: "^4.18.3",
      "lucide-react": "^0.356.0",
      react: "^18.2.0",
      "react-dom": "^18.2.0",
      "react-hook-form": "^7.51.1",
      "tailwind-merge": "^2.2.1",
      "tailwindcss-animate": "^1.0.7",
      wouter: "^3.1.0",
      zod: "^3.22.4"
    },
    devDependencies: {
      "@types/express": "^4.17.21",
      "@types/node": "^20.11.25",
      "@types/react": "^18.2.64",
      "@types/react-dom": "^18.2.21",
      "@vitejs/plugin-react": "^4.2.1",
      autoprefixer: "^10.4.18",
      concurrently: "^8.2.2",
      "drizzle-kit": "^0.20.14",
      postcss: "^8.4.35",
      tailwindcss: "^3.4.1",
      tsx: "^4.7.1",
      typescript: "^5.4.2",
      vite: "^5.1.6"
    }
  }, null, 2);
}

export function generateReadme(projectName: string, dataModel: DataModel): string {
  let readme = `# ${projectName}

A full-stack application generated by LocalForge.

## Tech Stack

- **Frontend**: React + TypeScript + Tailwind CSS
- **Backend**: Express.js
- **Database**: PostgreSQL with Drizzle ORM

## Getting Started

### Prerequisites

- Node.js 18+
- PostgreSQL database (or Neon serverless)

### Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Set up your database connection in \`.env\`:
   \`\`\`
   DATABASE_URL=postgresql://user:password@host:5432/database
   \`\`\`

3. Push the database schema:
   \`\`\`bash
   npm run db:push
   \`\`\`

4. Start the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

## Data Model

`;

  for (const entity of dataModel.entities) {
    readme += `### ${entity.name}\n\n`;
    readme += '| Field | Type | Required |\n';
    readme += '|-------|------|----------|\n';
    for (const field of entity.fields) {
      readme += `| ${field.name} | ${field.type} | ${field.required ? 'Yes' : 'No'} |\n`;
    }
    readme += '\n';
  }

  readme += `
## API Endpoints

`;

  for (const entity of dataModel.entities) {
    const routePath = toKebabCase(pluralize(entity.name));
    readme += `### ${entity.name}\n\n`;
    readme += `- \`GET /api/${routePath}\` - List all\n`;
    readme += `- \`GET /api/${routePath}/:id\` - Get one\n`;
    readme += `- \`POST /api/${routePath}\` - Create\n`;
    readme += `- \`PUT /api/${routePath}/:id\` - Update\n`;
    readme += `- \`DELETE /api/${routePath}/:id\` - Delete\n\n`;
  }

  return readme;
}
